### ISSUE TITLE
图片文件不要打包到exe里面, 要放在exe同一层的文件夹里面

### ISSUE THREAD

**Issue by hefju** [hefju/TSAutomatic#1]
图片越来越多, 不可能把所有的图片都打包到exe里面.  小量图标没有所谓.

**Comment by XXXSEOXXX** [comment]
图片不直接导入和放入资源，直接用代码引用路径j

**Comment by hefju** [comment]
例子: this.BackgroundImage = Image.FromFile("loginpic2.JPG");
